/*
  # Chale AI Integration Schema Extensions
  
  This migration extends the existing schema to support:
  1. Per-student generated content from Chale AI
  2. Enhanced progress tracking with detailed analytics
  3. Cultural context and curriculum alignment tracking
  4. Content generation metadata and versioning
  
  Key Changes:
  - Add student_modules, student_topics, student_exercises, student_questions tables
  - Extend user_progress with detailed tracking
  - Add content generation metadata
  - Add cultural context and curriculum alignment fields
*/

-- ============================================================================
-- STUDENT-SPECIFIC CONTENT TABLES
-- ============================================================================

-- Student-specific modules generated by Chale AI
CREATE TABLE IF NOT EXISTS student_modules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  subject TEXT NOT NULL CHECK (subject IN ('english', 'mathematics')),
  grade_level INTEGER NOT NULL CHECK (grade_level BETWEEN 4 AND 6),
  difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  cultural_context TEXT, -- Ghanaian cultural elements included
  curriculum_alignment TEXT, -- Ghana curriculum standards alignment
  generated_by TEXT NOT NULL DEFAULT 'chale-ai',
  generation_prompt TEXT, -- Original prompt used for generation
  chale_response JSONB, -- Full Chale AI response
  syto_formatted JSONB, -- Syto app formatted content
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (student_id, title, subject, grade_level)
);

-- Student-specific topics within modules
CREATE TABLE IF NOT EXISTS student_topics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  student_module_id UUID NOT NULL REFERENCES student_modules(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  content TEXT NOT NULL,
  order_index INTEGER NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  cultural_context TEXT,
  curriculum_alignment TEXT,
  generated_by TEXT NOT NULL DEFAULT 'chale-ai',
  generation_prompt TEXT,
  chale_response JSONB,
  syto_formatted JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (student_id, student_module_id, order_index)
);

-- Student-specific exercises within topics
CREATE TABLE IF NOT EXISTS student_exercises (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  student_topic_id UUID NOT NULL REFERENCES student_topics(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  type TEXT NOT NULL CHECK (type IN ('multiple-choice', 'fill-in-blank', 'matching', 'problem-solving', 'creative-writing', 'reading-comprehension')),
  order_index INTEGER NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  cultural_context TEXT,
  curriculum_alignment TEXT,
  generated_by TEXT NOT NULL DEFAULT 'chale-ai',
  generation_prompt TEXT,
  chale_response JSONB,
  syto_formatted JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (student_id, student_topic_id, order_index)
);

-- Student-specific questions within exercises
CREATE TABLE IF NOT EXISTS student_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  student_exercise_id UUID NOT NULL REFERENCES student_exercises(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  question_type TEXT NOT NULL CHECK (question_type IN ('multiple-choice', 'true-false', 'fill-in-blank', 'short-answer', 'essay', 'matching')),
  options JSONB, -- For multiple choice, matching, etc.
  correct_answer TEXT NOT NULL,
  explanation TEXT,
  hints TEXT[],
  order_index INTEGER NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  cultural_context TEXT,
  curriculum_alignment TEXT,
  generated_by TEXT NOT NULL DEFAULT 'chale-ai',
  generation_prompt TEXT,
  chale_response JSONB,
  syto_formatted JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (student_id, student_exercise_id, order_index)
);

-- ============================================================================
-- ENHANCED PROGRESS TRACKING
-- ============================================================================

-- Detailed student progress tracking
CREATE TABLE IF NOT EXISTS student_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Content references (can be either shared or student-specific)
  module_id TEXT REFERENCES modules(id) ON DELETE CASCADE,
  topic_id TEXT REFERENCES topics(id) ON DELETE CASCADE,
  exercise_id TEXT REFERENCES exercises(id) ON DELETE CASCADE,
  question_id TEXT REFERENCES questions(id) ON DELETE CASCADE,
  
  -- Student-specific content references
  student_module_id UUID REFERENCES student_modules(id) ON DELETE CASCADE,
  student_topic_id UUID REFERENCES student_topics(id) ON DELETE CASCADE,
  student_exercise_id UUID REFERENCES student_exercises(id) ON DELETE CASCADE,
  student_question_id UUID REFERENCES student_questions(id) ON DELETE CASCADE,
  
  -- Progress details
  status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'completed', 'skipped', 'needs_review')),
  score INTEGER CHECK (score >= 0 AND score <= 100),
  attempts INTEGER DEFAULT 0,
  time_spent_seconds INTEGER DEFAULT 0,
  student_answer TEXT,
  is_correct BOOLEAN,
  hints_used INTEGER DEFAULT 0,
  
  -- Timestamps
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  last_accessed_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Ensure we're tracking either shared or student-specific content, not both
  CONSTRAINT progress_content_check CHECK (
    (module_id IS NOT NULL OR student_module_id IS NOT NULL) AND
    NOT (module_id IS NOT NULL AND student_module_id IS NOT NULL)
  )
);

-- ============================================================================
-- LEARNING ANALYTICS AND INSIGHTS
-- ============================================================================

-- Track learning patterns and insights for each student
CREATE TABLE IF NOT EXISTS student_learning_analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  subject TEXT NOT NULL CHECK (subject IN ('english', 'mathematics')),
  
  -- Performance metrics
  total_questions_attempted INTEGER DEFAULT 0,
  total_questions_correct INTEGER DEFAULT 0,
  average_score DECIMAL(5,2) DEFAULT 0,
  total_time_spent_seconds INTEGER DEFAULT 0,
  
  -- Learning patterns
  preferred_difficulty TEXT CHECK (preferred_difficulty IN ('easy', 'medium', 'hard')),
  strong_topics TEXT[],
  weak_topics TEXT[],
  learning_streak_days INTEGER DEFAULT 0,
  last_activity_date DATE,
  
  -- Cultural engagement
  cultural_content_engagement_score DECIMAL(5,2) DEFAULT 0,
  favorite_cultural_contexts TEXT[],
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE (student_id, subject)
);

-- ============================================================================
-- CONTENT GENERATION TRACKING
-- ============================================================================

-- Track all content generation requests and responses
CREATE TABLE IF NOT EXISTS chale_generation_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  generation_type TEXT NOT NULL CHECK (generation_type IN ('module', 'topic', 'exercise', 'question', 'learning_path', 'assessment', 'cultural_content')),
  
  -- Request details
  request_data JSONB NOT NULL,
  generation_prompt TEXT NOT NULL,
  
  -- Response details
  chale_response JSONB,
  syto_formatted JSONB,
  generation_success BOOLEAN NOT NULL DEFAULT false,
  error_message TEXT,
  
  -- Performance metrics
  generation_time_ms INTEGER,
  tokens_used INTEGER,
  
  -- Content references (populated after successful generation)
  generated_module_id UUID REFERENCES student_modules(id),
  generated_topic_id UUID REFERENCES student_topics(id),
  generated_exercise_id UUID REFERENCES student_exercises(id),
  generated_question_id UUID REFERENCES student_questions(id),
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- Student content indexes
CREATE INDEX IF NOT EXISTS student_modules_student_id_idx ON student_modules(student_id);
CREATE INDEX IF NOT EXISTS student_modules_subject_grade_idx ON student_modules(subject, grade_level);
CREATE INDEX IF NOT EXISTS student_topics_student_id_idx ON student_topics(student_id);
CREATE INDEX IF NOT EXISTS student_topics_module_id_idx ON student_topics(student_module_id);
CREATE INDEX IF NOT EXISTS student_exercises_student_id_idx ON student_exercises(student_id);
CREATE INDEX IF NOT EXISTS student_exercises_topic_id_idx ON student_exercises(student_topic_id);
CREATE INDEX IF NOT EXISTS student_questions_student_id_idx ON student_questions(student_id);
CREATE INDEX IF NOT EXISTS student_questions_exercise_id_idx ON student_questions(student_exercise_id);

-- Progress tracking indexes
CREATE INDEX IF NOT EXISTS student_progress_student_id_idx ON student_progress(student_id);
CREATE INDEX IF NOT EXISTS student_progress_status_idx ON student_progress(status);
CREATE INDEX IF NOT EXISTS student_progress_completed_at_idx ON student_progress(completed_at);
CREATE INDEX IF NOT EXISTS student_progress_last_accessed_idx ON student_progress(last_accessed_at);

-- Analytics indexes
CREATE INDEX IF NOT EXISTS learning_analytics_student_id_idx ON student_learning_analytics(student_id);
CREATE INDEX IF NOT EXISTS learning_analytics_subject_idx ON student_learning_analytics(subject);
CREATE INDEX IF NOT EXISTS learning_analytics_last_activity_idx ON student_learning_analytics(last_activity_date);

-- Generation log indexes
CREATE INDEX IF NOT EXISTS generation_log_student_id_idx ON chale_generation_log(student_id);
CREATE INDEX IF NOT EXISTS generation_log_type_idx ON chale_generation_log(generation_type);
CREATE INDEX IF NOT EXISTS generation_log_created_at_idx ON chale_generation_log(created_at);

-- ============================================================================
-- ROW LEVEL SECURITY POLICIES
-- ============================================================================

-- Enable RLS on all new tables
ALTER TABLE student_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_learning_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE chale_generation_log ENABLE ROW LEVEL SECURITY;

-- Student content policies - students can only access their own content
CREATE POLICY "Students can view own modules"
  ON student_modules FOR SELECT
  TO authenticated
  USING (auth.uid() = student_id);

CREATE POLICY "Students can insert own modules"
  ON student_modules FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = student_id);

CREATE POLICY "Students can update own modules"
  ON student_modules FOR UPDATE
  TO authenticated
  USING (auth.uid() = student_id);

-- Similar policies for topics
CREATE POLICY "Students can view own topics"
  ON student_topics FOR SELECT
  TO authenticated
  USING (auth.uid() = student_id);

CREATE POLICY "Students can insert own topics"
  ON student_topics FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = student_id);

CREATE POLICY "Students can update own topics"
  ON student_topics FOR UPDATE
  TO authenticated
  USING (auth.uid() = student_id);

-- Similar policies for exercises
CREATE POLICY "Students can view own exercises"
  ON student_exercises FOR SELECT
  TO authenticated
  USING (auth.uid() = student_id);

CREATE POLICY "Students can insert own exercises"
  ON student_exercises FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = student_id);

CREATE POLICY "Students can update own exercises"
  ON student_exercises FOR UPDATE
  TO authenticated
  USING (auth.uid() = student_id);

-- Similar policies for questions
CREATE POLICY "Students can view own questions"
  ON student_questions FOR SELECT
  TO authenticated
  USING (auth.uid() = student_id);

CREATE POLICY "Students can insert own questions"
  ON student_questions FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = student_id);

CREATE POLICY "Students can update own questions"
  ON student_questions FOR UPDATE
  TO authenticated
  USING (auth.uid() = student_id);

-- Progress tracking policies
CREATE POLICY "Students can view own progress"
  ON student_progress FOR SELECT
  TO authenticated
  USING (auth.uid() = student_id);

CREATE POLICY "Students can insert own progress"
  ON student_progress FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = student_id);

CREATE POLICY "Students can update own progress"
  ON student_progress FOR UPDATE
  TO authenticated
  USING (auth.uid() = student_id);

-- Analytics policies
CREATE POLICY "Students can view own analytics"
  ON student_learning_analytics FOR SELECT
  TO authenticated
  USING (auth.uid() = student_id);

CREATE POLICY "Students can insert own analytics"
  ON student_learning_analytics FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = student_id);

CREATE POLICY "Students can update own analytics"
  ON student_learning_analytics FOR UPDATE
  TO authenticated
  USING (auth.uid() = student_id);

-- Generation log policies
CREATE POLICY "Students can view own generation log"
  ON chale_generation_log FOR SELECT
  TO authenticated
  USING (auth.uid() = student_id);

CREATE POLICY "Students can insert own generation log"
  ON chale_generation_log FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = student_id);

-- ============================================================================
-- FUNCTIONS FOR ANALYTICS AND INSIGHTS
-- ============================================================================

-- Function to update learning analytics after progress changes
CREATE OR REPLACE FUNCTION update_learning_analytics()
RETURNS TRIGGER AS $$
BEGIN
  -- Update analytics when progress is recorded
  INSERT INTO student_learning_analytics (student_id, subject, total_questions_attempted, total_questions_correct, last_activity_date)
  SELECT 
    NEW.student_id,
    CASE 
      WHEN sm.subject IS NOT NULL THEN sm.subject
      WHEN m.subject IS NOT NULL THEN m.subject
      ELSE 'english' -- default fallback
    END as subject,
    1, -- questions attempted
    CASE WHEN NEW.is_correct THEN 1 ELSE 0 END, -- questions correct
    CURRENT_DATE
  FROM student_progress sp
  LEFT JOIN student_modules sm ON sp.student_module_id = sm.id
  LEFT JOIN modules m ON sp.module_id = m.id
  WHERE sp.id = NEW.id
  ON CONFLICT (student_id, subject) 
  DO UPDATE SET
    total_questions_attempted = student_learning_analytics.total_questions_attempted + 1,
    total_questions_correct = student_learning_analytics.total_questions_correct + CASE WHEN NEW.is_correct THEN 1 ELSE 0 END,
    average_score = (student_learning_analytics.total_questions_correct::decimal + CASE WHEN NEW.is_correct THEN 1 ELSE 0 END) / 
                   (student_learning_analytics.total_questions_attempted + 1) * 100,
    last_activity_date = CURRENT_DATE,
    updated_at = NOW();
    
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update analytics
CREATE TRIGGER update_analytics_trigger
  AFTER INSERT OR UPDATE ON student_progress
  FOR EACH ROW
  EXECUTE FUNCTION update_learning_analytics();

-- Function to get student's learning path progress
CREATE OR REPLACE FUNCTION get_student_learning_path_progress(student_uuid UUID, subject_name TEXT)
RETURNS TABLE (
  module_title TEXT,
  module_progress DECIMAL,
  topics_completed INTEGER,
  total_topics INTEGER,
  exercises_completed INTEGER,
  total_exercises INTEGER,
  questions_completed INTEGER,
  total_questions INTEGER,
  average_score DECIMAL
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    sm.title as module_title,
    COALESCE(
      (SELECT COUNT(*)::decimal / NULLIF(COUNT(*) FILTER (WHERE sp.status = 'completed'), 0) * 100
       FROM student_progress sp 
       WHERE sp.student_id = student_uuid AND sp.student_module_id = sm.id), 
      0
    ) as module_progress,
    (SELECT COUNT(*)::integer FROM student_progress sp 
     JOIN student_topics st ON sp.student_topic_id = st.id
     WHERE sp.student_id = student_uuid AND st.student_module_id = sm.id AND sp.status = 'completed') as topics_completed,
    (SELECT COUNT(*)::integer FROM student_topics st WHERE st.student_module_id = sm.id) as total_topics,
    (SELECT COUNT(*)::integer FROM student_progress sp 
     JOIN student_exercises se ON sp.student_exercise_id = se.id
     JOIN student_topics st ON se.student_topic_id = st.id
     WHERE sp.student_id = student_uuid AND st.student_module_id = sm.id AND sp.status = 'completed') as exercises_completed,
    (SELECT COUNT(*)::integer FROM student_exercises se 
     JOIN student_topics st ON se.student_topic_id = st.id
     WHERE st.student_module_id = sm.id) as total_exercises,
    (SELECT COUNT(*)::integer FROM student_progress sp 
     JOIN student_questions sq ON sp.student_question_id = sq.id
     JOIN student_exercises se ON sq.student_exercise_id = se.id
     JOIN student_topics st ON se.student_topic_id = st.id
     WHERE sp.student_id = student_uuid AND st.student_module_id = sm.id AND sp.status = 'completed') as questions_completed,
    (SELECT COUNT(*)::integer FROM student_questions sq 
     JOIN student_exercises se ON sq.student_exercise_id = se.id
     JOIN student_topics st ON se.student_topic_id = st.id
     WHERE st.student_module_id = sm.id) as total_questions,
    COALESCE(
      (SELECT AVG(sp.score) FROM student_progress sp 
       JOIN student_questions sq ON sp.student_question_id = sq.id
       JOIN student_exercises se ON sq.student_exercise_id = se.id
       JOIN student_topics st ON se.student_topic_id = st.id
       WHERE sp.student_id = student_uuid AND st.student_module_id = sm.id AND sp.score IS NOT NULL), 
      0
    ) as average_score
  FROM student_modules sm
  WHERE sm.student_id = student_uuid AND sm.subject = subject_name
  ORDER BY sm.created_at;
END;
$$ LANGUAGE plpgsql;
